pitak/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField, SelectField, BooleanField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Заголовок', validators=[DataRequired()])
    transport_type = SelectField('Вид траспорта',
                                 choices=[('манипулятор', 'манипулятор'),
                                          ('автобетононасос', 'автобетононасос'),
                                          ('автобетоносмеситель', 'автобетоносмеситель'),
                                          ('эвакуатор', 'эвакуатор'), ('экскаватор', 'экскаватор'),
                                          ('автовышка', 'автовышка'), ('автокран', 'автокран'),
                                          ('мусоровоз', 'мусоровоз'), ('бензовоз', 'бензовоз'),
                                          ('погрузчик-манипулятор', 'погрузчик-манипулятор'),
                                          ('трактор', 'трактор'), ('цементовоз', 'цементовоз'),
                                          ('погрузчик вилочный', 'погрузчик вилочный')], validators=[DataRequired()])

    city = SelectField('Город', choices=[('Алматы', 'Алматы'), ('Нур-Султан', 'Нур-Султан'),
                                         ('Шымкент', 'Шымкент'), ('Тараз', 'Тараз'), ('Актау', 'Актау'),
                                         ('Актобе', 'Актобе'), ('Караганда', 'Караганда'),
                                         ('Павлодар', 'Павлодар'), ('Усть-Каменогорск', 'Усть-Каменогорск'),
                                         ('Семей', 'Семей'), ('Атырау', 'Атырау'),
                                         ('Петропавловск', 'Петропавловск'), ('Уральск,', 'Уральск,'),
                                         ('Талдыкорган', 'Талдыкорган'),
                                         ('Кызылорда', 'Кызылорда'), ('Кокшетау', 'Кокшетау')],
                       validators=[DataRequired()])
    description = TextAreaField('Описание объявления', validators=[DataRequired()])

    available = BooleanField('Свободен')

    image = FileField('Загрузите фото',
                        validators=[
                            FileAllowed(['jpg', 'png', 'jpeg'], 'Файл не имеет утвержденного расширения: jpg, png.')])

    submit = SubmitField('Опубликовать')

pitak/main/routes.py
from flask import render_template, Blueprint

main = Blueprint('main', __name__)


# @main.route("/")
# @main.route("/home")
# def home():
#     return render_template('home.html')


@main.route("/about")
def about():
    return render_template('about.html', title='О нас')

pitak/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from pitak import db
from pitak.models import Post, Comment
from pitak.posts.forms import PostForm
from pitak.posts.utils import save_image

posts = Blueprint('posts', __name__)


@posts.route("/")
# @login_required
def poster():
    q = request.args.get('q')

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.description.contains(q) |
                                  Post.city.contains(q) | Post.transport_type.contains(q))
    else:
        # posts = Post.query.all()
        posts = Post.query.order_by(Post.date_posted.desc())

    pages = posts.paginate(page=page, per_page=5)

    return render_template('posts.html', posts=posts, pages=pages, title='Объявления')


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        if form.image.data:
            image_file = save_image(form.image.data)
            form.image.data = image_file
        post = Post(title=form.title.data, transport_type=form.transport_type.data,
                    city=form.city.data, description=form.description.data,
                    image_file=form.image.data, available=form.available.data,
                    author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Ваше объявление создано!', 'success')
        return redirect(url_for('posts.poster'))
    return render_template('create_post.html', title='Подать объявление',
                           form=form, legend='Подать объявление')


@posts.route("/my-posts")
def my_posts():
    posts = current_user.posts
    return render_template('my_posts.html', posts=posts, title='Мои объявления')


@posts.route("/my-posts/<int:post_id>")
def my_post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/my-posts/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_my_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.transport_type = form.transport_type.data
        post.city = form.city.data
        post.description = form.description.data
        post.available = form.available.data
        db.session.commit()
        flash('Объявление успешно отредактирован!', 'success')
        return redirect(url_for('posts.my_post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.transport_type.data = post.transport_type
        form.city.data = post.city
        form.description.data = post.description
    return render_template('create_post.html', title='Редактировать объявление', form=form,
                           legend='Редактировать объявление')


@posts.route("/my-posts/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_my_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Объявление успешно удален!', 'success')
    return redirect(url_for('posts.my_posts'))


@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    comments = Comment.query.filter_by(post_id=post.id).all()
    post.views += 1

    if request.method == 'POST':
        message = request.form.get('message')
        comment = Comment(fullname=current_user.fullname, email=current_user.email,
                          image_file=current_user.image_file, message=message, post_id=post.id)
        db.session.add(comment)
        flash('Ваш комментарий отправлен!', 'success')
        post.comments += 1
        db.session.commit()
        return redirect(request.url)
    return render_template('post.html', title=post.title, post=post, comments=comments)

pitak/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from pitak import db, bcrypt
from pitak.models import User
from pitak.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from pitak.users.utils import save_image, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(fullname=form.fullname.data, email=form.email.data, phone_number=form.phone_number.data,
                    password=hashed_password, transporter=form.transporter.data)
        db.session.add(user)
        db.session.commit()
        flash('Ваша учетная запись была создана! Теперь вы можете войти в систему', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Регистрация', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.poster'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('posts.poster'))
        else:
            flash('Вход в систему не удался. Пожалуйста, проверьте адрес электронной почты и пароль', 'danger')
    return render_template('login.html', title='Авторизация', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('posts.poster'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.image.data:
            image_file = save_image(form.image.data)
            current_user.image_file = image_file
        current_user.fullname = form.fullname.data
        current_user.email = form.email.data
        current_user.phone_number = form.phone_number.data
        db.session.commit()
        flash('Ваша учетная запись была обновлена!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.fullname.data = current_user.fullname
        form.email.data = current_user.email
        form.phone_number.data = current_user.phone_number
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Профиль', image_file=image_file, form=form)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('posts.poster'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('На вашу электронную почту были отправлены инструкции по сбросу пароля.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Восстановление пароля', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('posts.poster'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Это недопустимый или просроченный токен', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Ваш пароль был обновлен! Теперь вы можете войти в систему', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Восстановление пароля', form=form)

pitak/templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/header.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forgetPassword.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap/css/bootstrap.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    {% if title %}
    <title>Pitak - {{ title }}</title>
    {% else %}
    <title>Pitak</title>
    {% endif %}
</head>
<body>
<div class="header navbar navbar-expand-lg navbar-dark pb-0 pt-0">
    <div class="container">
        <div class="d-flex justify-content-between flag">
            <a href="{{ url_for('posts.poster') }}" class="navbar-brand"><img
                    src="{{ url_for('static', filename='images/logo.svg') }}"
                    class="logo"
                    alt=""></a>
            <div class="d-flex d-md-none langwrap justify-content-end">
                <select class="form-select lang" aria-label="Default select example">
                    <option selected value="RU">RU &nbsp🇷🇺</option>
                    <option value="KZ">KZ &nbsp🇰🇿</option>
                </select>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav justify-content-between align-items-center w-100">
                <li class="nav-item me-md-5 me-0 mb-3 mb-md-0 mt-3 mt-md-0">
                    <a href="">НОВОСТИ</a>
                </li>
                <li class="nav-item me-md-auto me-0 mb-3 mb-md-0">
                    <a href="{{ url_for('main.about') }}">О НАС</a>
                </li>
                <li class="nav-item d-md-block d-none">
                    <div class="d-flex langwrap justify-content-end w-100">
                        <select class="form-select w-100" aria-label="Default select example">
                            <option selected value="RU">RU &nbsp🇷🇺</option>
                            <option value="KZ">KZ &nbsp🇰🇿</option>
                        </select>
                    </div>
                </li>
                <li class="nav-item ms-md-5 ms-0">
                    <div class="buttons d-flex flex-md-row flex-column">
                        {% if current_user.is_authenticated %}
                        <div class="accordion mb-3 mb-md-0 position-relative" id="accordion-menu">
                            <div class="accordion-item position-relative">
                                <h2 class="accordion-header position-relative" id="headingOne">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                            data-bs-target="#collapseOne" aria-expanded="true"
                                            aria-controls="collapseOne">
                                        {{ current_user.fullname }}
                                    </button>
                                </h2>
                                <div id="collapseOne" class="accordion-collapse collapse position-absolute w-100" aria-labelledby="headingOne"
                                     data-bs-parent="#accordion-menu">
                                    <div class="accordion-body d-flex flex-column w-100">
                                        <a href="{{ url_for('users.account') }}">Профиль</a>
                                        {% if current_user.transporter == 1 %}
                                        <a href="{{ url_for('posts.my_posts') }}">Мои объявления</a>
                                        {% endif %}
                                        <!--                        <a href="">Избранные</a>-->
                                        <a href="{{ url_for('users.logout') }}">Выйти</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% if current_user.transporter == 1 %}
                        <a href="{{ url_for('posts.new_post') }}" class="btn btn-primary add-post ms-md-4 ms-0 w-100 mb-3 mb-md-0">Подать
                            объявление</a>
                        {% endif %}
                        {% else %}
                        <a class="mb-3 mb-md-0" href="{{ url_for('users.login') }}" id="signin">Войти</a>
                        <a class="mb-3 mb-md-0 ms-md-4 ms-0" href="{{ url_for('users.register') }}" id="signup">Зарегестрироваться</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<!--<div class="container2 header d-flex justify-content-between">-->
<!--    <a href="javascript:void(0);" onclick="myFunction()" class="mobmenu" id="mobmenu">-->
<!--        <img src="{{ url_for('static', filename='images/menu.svg')}}"/>-->
<!--        <img src="{{ url_for('static', filename='images/menu.svg')}}"/>-->
<!--        <img src="{{ url_for('static', filename='images/menu.svg')}}"/>-->
<!--    </a>-->
<!--    <a href="{{ url_for('posts.poster') }}"><img src="{{ url_for('static', filename='images/logo.svg') }}" class="logo"-->
<!--                                                 alt=""></a>-->
<!--    <ul>-->
<!--        <li><a href="">НОВОСТИ</a></li>-->
<!--        <li><a href="{{ url_for('main.about') }}">О НАС</a></li>-->
<!--    </ul>-->
<!--    <div class="d-flex langwrap justify-content-end">-->
<!--        <select class="form-select" aria-label="Default select example">-->
<!--            <option selected value="RU">RU &nbsp🇷🇺</option>-->
<!--            <option value="KZ">KZ &nbsp🇰🇿</option>-->
<!--        </select>-->
<!--    </div>-->
<!--    <div class="buttons">-->
<!--        {% if current_user.is_authenticated %}-->
<!--        <div class="accordion" id="accordion-menu">-->
<!--            <div class="accordion-item">-->
<!--                <h2 class="accordion-header" id="headingOne">-->
<!--                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"-->
<!--                            data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">-->
<!--                        {{ current_user.fullname }}-->
<!--                    </button>-->
<!--                </h2>-->
<!--                <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne"-->
<!--                     data-bs-parent="#accordion-menu">-->
<!--                    <div class="accordion-body d-flex flex-column">-->
<!--                        <a href="{{ url_for('users.account') }}">Профиль</a>-->
<!--                        {% if current_user.transporter == 1 %}-->
<!--                        <a href="{{ url_for('posts.my_posts') }}">Мои объявления</a>-->
<!--                        {% endif %}-->
<!--                        &lt;!&ndash;                        <a href="">Избранные</a>&ndash;&gt;-->
<!--                        <a href="{{ url_for('users.logout') }}">Выйти</a>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--        {% if current_user.transporter == 1 %}-->
<!--        <a href="{{ url_for('posts.new_post') }}" class="btn btn-primary" style="width: 160px; height: 40px">Подать-->
<!--            объявление</a>-->
<!--        {% endif %}-->
<!--        {% else %}-->
<!--        <a href="{{ url_for('users.login') }}" id="signin">Войти</a>-->
<!--        <a href="{{ url_for('users.register') }}" id="signup">Зарегестрироваться</a>-->
<!--        {% endif %}-->
<!--    </div>-->
<!--</div>-->
<div class="topnav" id="myTopnav">
    <div class="logo"><img src="style/img/logo.svg"></img></div>
    <hr>
    <ul>
        <li href="#">НОВОСТИ</li>
        <li href="#">О НАС</li>
    </ul>
    <a href="#" id="signin">Войти</a>
    <a href="signup.html" id="signup">Зарегестрироваться</a>

</div>
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }} mb-0">
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}
{% block content %}

{% endblock %}
<footer class="container2">
    <div class="footerContent container">
        <a href="{{ url_for('main.about') }}">О НАС</a>
        <a href="#">НОВОСТИ</a>
        <div class="contacts">
            <p>КОНТАКТЫ</p>
            <div>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="white" class="bi bi-geo-alt"
                     viewBox="0 0 16 16">
                    <path d="M12.166 8.94c-.524 1.062-1.234 2.12-1.96 3.07A31.493 31.493 0 0 1 8 14.58a31.481 31.481 0 0 1-2.206-2.57c-.726-.95-1.436-2.008-1.96-3.07C3.304 7.867 3 6.862 3 6a5 5 0 0 1 10 0c0 .862-.305 1.867-.834 2.94zM8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10z"/>
                    <path d="M8 8a2 2 0 1 1 0-4 2 2 0 0 1 0 4zm0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                </svg>
                <p>г. Алматы, Бостандыкский район, улица Ауэзова 179а</p>
            </div>
            <div>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="white"
                     class="bi bi-telephone" viewBox="0 0 16 16">
                    <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
                </svg>
                <p>+7 707 402 00 24, пн-пт (09:00 – 18:00)</p>
            </div>
            <div>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="white"
                     class="bi bi-envelope" viewBox="0 0 16 16">
                    <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2zm13 2.383-4.758 2.855L15 11.114v-5.73zm-.034 6.878L9.271 8.82 8 9.583 6.728 8.82l-5.694 3.44A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.739zM1 11.114l4.758-2.876L1 5.383v5.73z"/>
                </svg>
                <p>ingruzovik@gmail.com</p>
            </div>
        </div>
    </div>
    <hr>
    <p>© 2020, INGRUZOVIK</p>
</footer>
<!--<script src="{{ url_for('static', filename='js/jquery.maskedinput.min.js') }}"></script>-->
<script src="https://unpkg.com/imask"></script>
<script src="{{ url_for('static', filename='js/script.js') }}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
<script type="text/javascript" src="js/script.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</body>
</html>

pitak/templates/post.html
{% extends "layout.html" %}

{% block content %}
<div class="container mt-4 detailed-post">
    <div class="d-flex flex-column">
        <div class="d-flex flex-row align-items-center">
            <img class="rounded-circle article-img"
                 src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" alt=""/>
            <div class="d-flex flex-md-row flex-column">
                <p class="fullname me-md-5 mb-md-0 mb-2">{{ post.author.fullname }}</p>
                <p class="phone-number me-md-5 mb-md-0 mb-2">Номер: <a href="tel:{{ post.author.phone_number }}">{{
                    post.author.phone_number }}</a></p>
                <p class="email">E-mail: <a href="">{{ post.author.email }}</a></p>
            </div>
        </div>
        <div class="d-flex flex-md-row flex-column justify-content-between mt-4">
            <div class="d-flex flex-column left mb-md-0 mb-4">
                <h2 class="title">{{ post.title }}</h2>
                <div class="d-flex flex-row mt-3">
                    <a class="me-4 transport-type">{{ post.transport_type }}</a>
                    <a class="city">{{ post.city }}</a>
                </div>
                <p class="description mt-4">
                    Описание
                    <br>
                    <br>
                    <span>
                        {{ post.description }}
                    </span>
                </p>
                <div class="d-flex flex-row mt-4 justify-content-between info">
                    <p>Просмотров: <span>{{ post.views }}</span></p>
                    <p class="text-md-start text-end">Дата публикации:
                        <span>{{ post.date_posted.strftime('%d.%m.%Y') }}</span></p>
                </div>
                {% if post.author == current_user %}
                <div class="d-flex flex-row justify-content-md-end update-delete mt-4">
                    <a href="{{ url_for('posts.update_my_post', post_id=post.id) }}"
                       class="btn update btn-outline-warning">Редактировать</a>
                    <button type="button" class="btn btn-outline-danger ms-4 delete" data-bs-toggle="modal"
                            data-bs-target="#deleteModal">Удалить
                    </button>
                </div>
                {% endif %}
            </div>
            <div class="d-flex right align-items-center">
                <img src="/static/post_pics/{{ post.image_file }}" alt="">
            </div>
        </div>
        <div class="d-flex flex-column comment mt-4">
            <p class="comment">Комментарий</p>
            <form action="" method="POST">
                <div class="form-floating">
                    <textarea class="form-control" name="message" placeholder="Leave a comment here"
                              id="floatingTextarea"></textarea>
                    <label for="floatingTextarea">Оставьте комментарий здесь</label>
                </div>
                <div class="d-flex justify-content-end mt-3">
                    <button type="submit" class="btn btn-primary send">Отправить</button>
                </div>
            </form>
        </div>
        <div class="d-flex flex-column w-50">
            {% for comment in comments %}
            <div class="d-flex flex-column border-bottom pb-3">
                <div class="d-flex flex-row align-items-center">
                    <img class="rounded-circle article-img"
                         src="{{ url_for('static', filename='profile_pics/' + comment.image_file) }}" alt=""/>
                    <div class="d-flex flex-column">
                        <p class="comment-name mb-2">{{ comment.fullname }}</p>
                        <p class="comment-message">{{ comment.message }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Удалить объявление?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                <form action="{{ url_for('posts.delete_my_post', post_id=post.id) }}" method="POST">
                    <input type="submit" class="btn btn-danger" value="Удалить">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

pitak/templates/reset_request.html
{% extends "layout.html" %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="d-flex flex-column register">
        <h2 class="mb-3 border-bottom pb-2">Восстановление пароля</h2>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.email.label(class="form-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control") }}
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.submit(class="btn btn-primary signin") }}
            </div>
        </form>
    </div>
</div>
{% endblock content%}